controller_list:
  - name: fake_default_group_controller
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
initial:  # Define initial robot poses.
  - group: default_group
    pose: home